### PR TITLE
Encrypted webm handling

### PR DESCRIPTION
**Pull request by SingingTree**
Parse encryption elements for WebMs (http://www.webmproject.org/docs/webm-encryption/).

High level blurb about additions and alterations:

1. New ebml_element_descs have been added and structures updated for newly added ebml relationships. The relationships added are:
  - track_entry now contains a content_encodings, a list of possible encodings (encryption code expects first content encoding to contain crypto info)
  - A content_encoding contains a content_encoding_type (encoding or encryption) and and a content_encryption list to be populated with one element if encryption info is present.
  - content_encryption contains a content_enc_algo, which we would expect to be AES as per spec (enforced with error code and logged message), a content_enc_key_id, and a content_enc_aes_settings. These elements are introduced as a WebM specific extension to the Matroska spec.
  - content_enc_aes_settings contains a single value: aes_settings_cipher_mode. This value should be set to 1 for CTR mode as per the spec (enforced via error code and logging).
2. ne_read_block has had logic added to parse encryption info.
  - I've added checking early in this function to make sure encryption elements are in line with the spec, if not -1 is returned and an error logged. I am not doing check on the signal byte. There are bits that the spec says are unused and should not be set, but I simply ignore them.
  - The frame structure has been updated to include encryption information. The frame struct now has a frame_encryption struct which contains the iv for that frame, the length of the iv, and the singnal byte (WebM specific encryption byte). I've updated the nestegg_free_packet function to handle the new members of frame.
3. nestegg_track_encryption has been added and is used to query track encryption info.
  - I tried to remain consistent with the existing track audio and video query functions. Calling convention remains the same, and a struct is exposed for the params relating to the function.
  - This function does checking on values being queried and will log and return an error on aberrant encryption settings.
4. nestegg_packet_encryption has been added and is used to query packet encryption info.
  - Attempts to remain consistent with other packet query functions.
  - Return codes indicate either packet has no signal byte (no encryption flags), has a signal byte and is encrypted, or has a signal byte and is unencrypted.
  - Asserts that the packets cannot be both laced and encrypted. A caller should never be given a pointer to a packet that is encrypted and laced, as parsing of blocks containing such packets should fail. As such, they should never be able to call this function with such a packet.
5. Tests have been updated to check track and packet encryption values (not all are checked, however), and a encrypted file has been added to the test media.

---
This change is [Reviewable](https://reviewable.io/reviews/kinetiknz/nestegg/36)

### CODE REVIEW

**Comment by kinetiknz** [comment]
Thanks, looking good.  A few comments and questions to address.

<details><summary><i>Previously, SingingTree wrote…</i></summary>
> #### Encrypted webm handling
> 
> Parse encryption elements for WebMs (http://www.webmproject.org/docs/webm-encryption/).
> 
> 
> 
> High level blurb about additions and alterations:
> 
> 
> 
> 1. New ebml_element_descs have been added and structures updated for newly added ebml relationships. The relationships added are:
> 
>   - track_entry now contains a content_encodings, a list of possible encodings (encryption code expects first content encoding to contain crypto info)
> 
>   - A content_encoding contains a content_encoding_type (encoding or encryption) and and a content_encryption list to be populated with one element if encryption info is present.
> 
>   - content_encryption contains a content_enc_algo, which we would expect to be AES as per spec (enforced with error code and logged message), a content_enc_key_id, and a content_enc_aes_settings. These elements are introduced as a WebM specific extension to the Matroska spec.
> 
>   - content_enc_aes_settings contains a single value: aes_settings_cipher_mode. This value should be set to 1 for CTR mode as per the spec (enforced via error code and logging).
> 
> 2. ne_read_block has had logic added to parse encryption info.
> 
>   - I've added checking early in this function to make sure encryption elements are in line with the spec, if not -1 is returned and an error logged. I am not doing check on the signal byte. There are bits that the spec says are unused and should not be set, but I simply ignore them.
> 
>   - The frame structure has been updated to include encryption information. The frame struct now has a frame_encryption struct which contains the iv for that frame, the length of the iv, and the singnal byte (WebM specific encryption byte). I've updated the nestegg_free_packet function to handle the new members of frame.
> 
> 3. nestegg_track_encryption has been added and is used to query track encryption info.
> 
>   - I tried to remain consistent with the existing track audio and video query functions. Calling convention remains the same, and a struct is exposed for the params relating to the function.
> 
>   - This function does checking on values being queried and will log and return an error on aberrant encryption settings.
> 
> 4. nestegg_packet_encryption has been added and is used to query packet encryption info.
> 
>   - Attempts to remain consistent with other packet query functions.
> 
>   - Return codes indicate either packet has no signal byte (no encryption flags), has a signal byte and is encrypted, or has a signal byte and is unencrypted.
> 
>   - Asserts that the packets cannot be both laced and encrypted. A caller should never be given a pointer to a packet that is encrypted and laced, as parsing of blocks containing such packets should fail. As such, they should never be able to call this function with such a packet.
> 
> 5. Tests have been updated to check track and packet encryption values (not all are checked, however), and a encrypted file has been added to the test media.
> 
> 
> 
</details>


---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[include/nestegg/nestegg.h, line 92 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0fRAIhDElzEAFX2CM:-KI0fRAIhDElzEAFX2CN:1579317186) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/include/nestegg/nestegg.h#L92)):*
> ```objc
> #define NESTEGG_LOG_CRITICAL 10000 /**< Critical level log message. */
> 
> #define NESTEGG_ENCODING_COMPRESSION 0 /**< Content encoding type is compression. */
> ```

This doesn't seem to be used anywhere, why add it to the header/API?

---

*[include/nestegg/nestegg.h, line 162 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0g6ALv3sv7puTTQLu:-KI0g6ALv3sv7puTTQLv:65322677) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/include/nestegg/nestegg.h#L162)):*
> ```objc
>   unsigned int content_encoding_type;
>   unsigned int content_enc_algo;
>   unsigned int aes_settings_cipher_mode;
> ```

Add defines for these fields so the API client isn't using magic values. 

---

*[include/nestegg/nestegg.h, line 164 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0ck5qCWzjS-lIzSSx:-KI0ck5qCWzjS-lIzSSy:-365742063) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/include/nestegg/nestegg.h#L164)):*
> ```objc
>   unsigned int aes_settings_cipher_mode;
>   unsigned char * content_enc_key_id;
>   uint64_t enc_key_id_length;
> ```

size_t and rename it to content_enc_key_id_length (or drop content_ from the other field).  Make content_enc_key_id const.

Document all of the fields, including noting that ownership of content_enc_key_id remains with the nestegg context and does not need to be freed separately.

---

*[include/nestegg/nestegg.h, line 411 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0f-H8f6jJJAQweKUR:-KI0f-H8f6jJJAQweKUS:-1642916698) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/include/nestegg/nestegg.h#L411)):*
> ```objc
>     @retval  0 No signal byte, encryption information not read from packet.
>     @retval  1 Encrypted bit set, encryption infomation read from packet.
>     @retval  2 Encrypted bit not set, encryption information not read from packet.
> ```

Do we need to distinguish between these cases? Would it be sufficient to return either success or error and have the client check whether the pointer is NULL instead?

If we do need these return values for some reason, they need to be defines rather than magic values.

---

*[include/nestegg/nestegg.h, line 413 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0esS8o5a-grlTnyrv:-KI0esS9t_2jY_VXr5CV:1776632128) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/include/nestegg/nestegg.h#L413)):*
> ```objc
>     @retval  2 Encrypted bit not set, encryption information not read from packet.
>     @retval -1 Error.*/
> int nestegg_packet_encryption(nestegg_packet * packet, unsigned char ** iv,
> ```

const the pointed-to data

---

*[src/nestegg.c, line 165 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0nv4oE4L8PTf5PyNB:-KI0nv4oE4L8PTf5PyNC:-931947494) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L165)):*
> ```C
> 
> /* Packet Encryption */
> #define SIGNAL_BYTE_SIZE            1
> ```

As much as I love defines to avoid magic numbers, I don't think we need one for the size of a byte.

---

*[src/nestegg.c, line 331 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0iBk53A-pbFyJ8zWl:-KI0iBk53A-pbFyJ8zWm:-673946641) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L331)):*
> ```C
> };
> 
> struct frame_encryption {
> ```

Just call it iv

---

*[src/nestegg.c, line 338 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0iDTG7F8dqZ2uwNQl:-KI0iDTG7F8dqZ2uwNQm:-1608581807) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L338)):*
> ```C
> 
> struct frame {
>   struct frame_encryption * frame_encryption;
> ```

Put this after data and length, before next.

Just embed the struct rather than adding another pointer + allocation; we can check if iv is NULL directly.

---

*[src/nestegg.c, line 1327 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0n-t3xigt9Vf-TAvs:-KI0n-t3xigt9Vf-TAvt:1094209121) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L1327)):*
> ```C
>   double track_scale;
>   uint64_t track_number, length, frame_sizes[256], cluster_tc, flags, frames, tc_scale, total,
>            encoding_type, encryption_algo, encryption_mode, data_size, encryption_size;
> ```

data_size and encryption_size should be size_t

---

*[src/nestegg.c, line 1428 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0mOBz5uufOfdaANQV:-KI0mOBz5uufOfdaANQW:1670963513) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L1428)):*
> ```C
> 
>   encoding_type = 0;
>   if (entry->content_encodings.content_encoding.head) {
> ```

Move this entire block into a helper function.

---

*[src/nestegg.c, line 1511 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0n7xqNVUgn_CbdsHC:-KI0n7xqNVUgn_CbdsHD:33433321) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L1511)):*
> ```C
>         free(f);
>         nestegg_free_packet(pkt);
>         return -1;
> ```

return r here

---

*[src/nestegg.c, line 1520 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0ng6dJU7Q3DNnQ-y1:-KI0ng6dJU7Q3DNnQ-y2:-1124318507) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L1520)):*
> ```C
>       }
>       f->frame_encryption->signal_byte = signal_byte;
>       if((signal_byte & ENCRYPTED_BIT_MASK) == PACKET_ENCRYPTED) {
> ```

Space between if and ((

---

*[src/nestegg.c, line 1550 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0oQDYaJcyDOAMnAaB:-KI0oQDYaJcyDOAMnAaC:1164307445) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L1550)):*
> ```C
>     f->data = ne_alloc(data_size);
>     if (!f->data) {
>       free(f);
> ```

The error handling after the point of the frame_encryption allocations needs to be updated to free the allocs on error.

---

*[src/nestegg.c, line 1557 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0ofeYlRWfIHtu7u0C:-KI0ofeYlRWfIHtu7u0D:-1209553044) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L1557)):*
> ```C
>     r = ne_io_read(ctx->io, f->data, data_size);
>     if (r != 1) {
>       free(f->data);
> ```

Ditto above.

---

*[src/nestegg.c, line 2581 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0ixPRUuVUsbS8kBsX:-KI0ixPRUuVUsbS8kBsY:784755497) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L2581)):*
> ```C
> 
>   if (!entry->content_encodings.content_encoding.head)
>     return 0;
> ```

Return an error here.  See comment below.

---

*[src/nestegg.c, line 2588 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0j0qEp_GN1_LGb_nM:-KI0j0qEp_GN1_LGb_nN:405508257) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L2588)):*
> ```C
>   ne_get_uint(encoding->content_encoding_type, &value);
>   if (value != NESTEGG_ENCODING_ENCRYPTION)
>     return 0;
> ```

Error here too.  Otherwise the meaning of the values of nestegg_encryption_params is very fuzzy when they're zero-initialized and this returns success.  Use multiple error values to distinguish between not-present and fatal error, if necessary.

---

*[src/nestegg.c, line 2921 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0fhrkjH_b2hHlrQEg:-KI0fhrkjH_b2hHlrQEh:1706164804) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L2921)):*
> ```C
>   *iv = NULL;
>   *length = 0;
>   if (f->frame_encryption) {
> ```

Invert the test and early return to avoid nesting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-:-KI0pK7KoUHtqBx9GHMk:-1078097360)*

**Comment by SingingTree** [comment]
Cheers. I've got a few questions that I've made in comments. Otherwise changes have been made and am just waiting on other changes. Also fixed that new test media was not added to regress.test.

<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> Thanks, looking good.  A few comments and questions to address.
</details>


---

Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[include/nestegg/nestegg.h, line 92 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0fRAIhDElzEAFX2CM:-KI1bBJqp2chyAPihKrM:-306453139) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/include/nestegg/nestegg.h#L92)):*
<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> This doesn't seem to be used anywhere, why add it to the header/API?
</details>
I've rolled this into the exposed API for the encryption params struct.

---

*[include/nestegg/nestegg.h, line 411 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0f-H8f6jJJAQweKUR:-KI4vVMisbjyQh7dTOS8:41904624) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/include/nestegg/nestegg.h#L411)):*
<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> Do we need to distinguish between these cases? Would it be sufficient to return either success or error and have the client check whether the pointer is NULL instead?
> 
> If we do need these return values for some reason, they need to be defines rather than magic values.
> 
> 
</details>
Will create defines for return values. This is useful to differentiate between non encrypted tracks and encrypted tracks but not encrypted tracks for upstream handling and population of encrypted data structures (or not depending on the case).

---

*[src/nestegg.c, line 165 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0nv4oE4L8PTf5PyNB:-KI4c-qMoRjJbNqEElyA:-1491462909) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L165)):*
<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> As much as I love defines to avoid magic numbers, I don't think we need one for the size of a byte.
</details>
I agree that it's pretty simplistic, but I think it makes the calculations later for the size of the encrypted part of blocks a lot more readable (SIGNAL_BYTE_SIZE + IV_SIZE kind of stuff). If you still think I should be removed I'll rework those calculations to be more clean sans define.

---

*[src/nestegg.c, line 331 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0iBk53A-pbFyJ8zWl:-KI4cgtSBIWqodOEbdUf:1427741123) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L331)):*
<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> Just call it iv
</details>
To be sure I understand: the entire struct? Any concerns over the iv.iv notation (could change to iv.data or some such), or that the signal_byte would then belong to the iv struct?

---

*[src/nestegg.c, line 338 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0iDTG7F8dqZ2uwNQl:-KI5B1PpdqwRRXoE7mS0:-1882389242) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L338)):*
<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> Put this after data and length, before next.
> 
> Just embed the struct rather than adding another pointer + allocation; we can check if iv is NULL directly.
</details>
Will do.

For the second case we'd need a way to indicate if the IV is null due to no encryption being read, or null due to encryption being read, but the frame being unencrypted (a flag?).

---

*[src/nestegg.c, line 2581 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0ixPRUuVUsbS8kBsX:-KI5n9uUPbp94Q9g0RtM:1728941923) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L2581)):*
<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> Return an error here.  See comment below.
</details>
Comment below.

---

*[src/nestegg.c, line 2588 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0j0qEp_GN1_LGb_nM:-KI5nCAzHQm0uNnoWjHh:1246591498) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L2588)):*
<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> Error here too.  Otherwise the meaning of the values of nestegg_encryption_params is very fuzzy when they're zero-initialized and this returns success.  Use multiple error values to distinguish between not-present and fatal error, if necessary.
</details>
I had intended the 0 values to mean that content was unencrypted. I'm mixing my metaphors a little here, the function is call track_encryption, but it returns the encoding, of which encryption is a specific type. I had imagined that the encoding field could be checked to determine if encryption is used or not. I could change the naming to better reflect this, or do you think I should proceed with your above recommendation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-:-KI5l1fSL9TgJwnbWyzI:-469556424)*

**Comment by kinetiknz** [comment]
Thanks, replies inline.  I've made your life slightly painful by merging my changes from bug1261900 into master, which will cause conflicts in nestegg_read_packet (at least) with your changes.  I can deal with the conflicts once your branch is ready to merge, if you prefer.

<details><summary><i>Previously, SingingTree (Bryce Van Dyk) wrote…</i></summary>
> Cheers. I've got a few questions that I've made in comments. Otherwise changes have been made and am just waiting on other changes. Also fixed that new test media was not added to regress.test.
</details>


---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[src/nestegg.c, line 165 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0nv4oE4L8PTf5PyNB:-KI68qYvYAEW6lmC5z2k:-1459361042) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L165)):*
<details><summary><i>Previously, SingingTree (Bryce Van Dyk) wrote…</i></summary>
> I agree that it's pretty simplistic, but I think it makes the calculations later for the size of the encrypted part of blocks a lot more readable (SIGNAL_BYTE_SIZE + IV_SIZE kind of stuff). If you still think I should be removed I'll rework those calculations to be more clean sans define.
</details>
Okay, let's keep it.

---

*[src/nestegg.c, line 331 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0iBk53A-pbFyJ8zWl:-KI69ROgb33wfqAxZqJZ:1943083417) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L331)):*
<details><summary><i>Previously, SingingTree (Bryce Van Dyk) wrote…</i></summary>
> To be sure I understand: the entire struct? Any concerns over the iv.iv notation (could change to iv.data or some such), or that the signal_byte would then belong to the iv struct?
</details>
Yeah, the struct.  I guess it's a bit weird to rename it iv and leave signal_byte in there; let's keep the name as-is.

---

*[src/nestegg.c, line 338 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0iDTG7F8dqZ2uwNQl:-KI6AquSN-Nz1r2q1EQz:8556839) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L338)):*
<details><summary><i>Previously, SingingTree (Bryce Van Dyk) wrote…</i></summary>
> Will do.
> 
> For the second case we'd need a way to indicate if the IV is null due to no encryption being read, or null due to encryption being read, but the frame being unencrypted (a flag?).
</details>
Hmm, exchanging a pointer for a flag probably isn't a net win, let's leave it as-is.

---

*[src/nestegg.c, line 2588 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0j0qEp_GN1_LGb_nM:-KI6B_RpgF0I1JnP90py:-1871083464) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L2588)):*
<details><summary><i>Previously, SingingTree (Bryce Van Dyk) wrote…</i></summary>
> I had intended the 0 values to mean that content was unencrypted. I'm mixing my metaphors a little here, the function is call track_encryption, but it returns the encoding, of which encryption is a specific type. I had imagined that the encoding field could be checked to determine if encryption is used or not. I could change the naming to better reflect this, or do you think I should proceed with your above recommendation?
</details>
Oh, I missed that this was overloaded.  I think I'd prefer two functions, one being track_encryption_params that fills out nestegg_encryption_params and succeeds or fails, and another that tells you the crypto type.

I think the same thing applies to nestegg_packet_encryption; split it into one to query the crypto type and another to retrieve the IV buffer (for the case where type would've been == 1).

Sound okay?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-:-KI6CK1Ub229JgipBFAJ:-1601878620)*

**Comment by SingingTree** [comment]
Cool, cheers for the heads up. I will attempt the merge and let you know if there's anything I'm uncertain of how to handle.

<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> Thanks, replies inline.  I've made your life slightly painful by merging my changes from bug1261900 into master, which will cause conflicts in nestegg_read_packet (at least) with your changes.  I can deal with the conflicts once your branch is ready to merge, if you prefer.
</details>


---

Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/nestegg.c, line 2588 \[r1\]](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-KI0j0qEp_GN1_LGb_nM:-KIA3O5nGWws1pyz9Yq1:463447916) ([raw file](https://github.com/kinetiknz/nestegg/blob/4431f897aeaaca3f4814a057ac3b2e609451d774/src/nestegg.c#L2588)):*
<details><summary><i>Previously, kinetiknz (Matthew Gregan) wrote…</i></summary>
> Oh, I missed that this was overloaded.  I think I'd prefer two functions, one being track_encryption_params that fills out nestegg_encryption_params and succeeds or fails, and another that tells you the crypto type.
> 
> I think the same thing applies to nestegg_packet_encryption; split it into one to query the crypto type and another to retrieve the IV buffer (for the case where type would've been == 1).
> 
> Sound okay?
</details>
Sounds good. Will do and should have an updated PR soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-:-KIA3VjaC3Frewk2PoQR:-1535724470)*

**Comment by SingingTree** [comment]
Updated. I've situated the new changes into their own commit for ease of differentiation. Aside from the changes discussed I've:
- Updated the tests to also call the -r option for the encrypted tests.
- Rolled all length variables in the tests together into length -- there was getting to be a lot of separate length vars which was bloating the declaration block.

<details><summary><i>Previously, SingingTree (Bryce Van Dyk) wrote…</i></summary>
> Cool, cheers for the heads up. I will attempt the merge and let you know if there's anything I'm uncertain of how to handle.
</details>


---

Review status: 10 of 15 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-:-KIP7FsiKfNMcxhBSS66:193478845)*

**Comment by kinetiknz** [comment]
:lgtm: Thanks!

<details><summary><i>Previously, SingingTree (Bryce Van Dyk) wrote…</i></summary>
> Updated. I've situated the new changes into their own commit for ease of differentiation. Aside from the changes discussed I've:
> - Updated the tests to also call the -r option for the encrypted tests.
> - Rolled all length variables in the tests together into length -- there was getting to be a lot of separate length vars which was bloating the declaration block.
</details>


---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kinetiknz/nestegg/36#-:-KIQ9K1Z5Q2_-YE44jY1:-971291639)*

**Comment by kinetiknz** [comment]
Merged in https://github.com/kinetiknz/nestegg/commit/3bc788d4de8f11a1e6b625047f49b9d35dce824f

**Pull request closed without merging**
